const scroll = [
  {
    id: 1,
    img: <img src='/picture/арбуз.jpg'/>,
    name: 1,
    st: false,
    st2: true,
  },
  {
    id:2,
    img: <img src='/picture/арбуз.jpg'/>,
    name:1,
    st: false,
    st2: true,
  },
  {
    id:3,
    img: <img src='/picture/авокадо2.jpg'/>,
    name:2,
    st: false,
    st2: true,
  },
  {
    id:4,
    img: <img src='/picture/авокадо2.jpg'/>,
    name:2,
    st: false,
    st2: true,
  },
  {
    id:5,
    img: <img src='/picture/кекс.jpg'/>,
    name:3,
    st: false,
    st2: true,
  },
  {
    id:6,
    img: <img src='/picture/кекс.jpg'/>,
    name:3,
    st: false,
    st2: true,
  },
  {
    id:7,
    img: <img src='/picture/облочко.jpg'/>,
    name:4,
    st: false,
    st2: true,
  },
  {
    id:8,
    img: <img src='/picture/облочко.jpg'/>,
    name:4,
    st: false,
    st2: true,
  },
  {
    id:9,
    img: <img src='/picture/пес.jpg'/>,
    name:5,
    st: false,
    st2: true,
  },
  {
    id:10,
    img: <img src='/picture/пес.jpg'/>,
    name:5,
    st: false,
    st2: true,
  },
  {
    id:11,
    img: <img src='/picture/хомечек.jpg'/>,
    name:6,
    st: false,
    st2: true,
  },
  {
    id:12,
    img: <img src='/picture/хомечек.jpg'/>,
    name:6,
    st: false,
    st2: true,
  },
  {
    id:13,
    img: <img src='/picture/яишенка.jpg'/>,
    name:7,
    st: false,
    st2: true,
  },
  {
    id:14,
    img: <img src='/picture/яишенка.jpg'/>,
    name:7,
    st: false,
    st2: true,
  },
  {
    id:15,
    img: <img src='/picture/жираф.jpg'/>,
    name:8,
    st: false,
    st2: true,
  },
  {
    id:16,
    img: <img src='/picture/жираф.jpg'/>,
    name:8,
    st: false,
    st2: true,
  },
]

export default scroll;
